---
# tasks file for k8s_init_master

- name: run kubeadm init
  command:
    argv:
      - kubeadm
      - init
      - "--pod-network-cidr={{ flannel_pod_net_cidr }}"
  register: kubeadm_init_out

- name: store kubeadm init output
  copy:
      content: "{{ kubeadm_init_out.stdout }}"
      dest: out.txt
  delegate: localhost
  when: kubeadm_init_out.changed



