- name: import docker gpg key
  apt_key:
    id: "{{ docker_key_id }}" 
    url: "{{ docker_key_url }}"
    state: present

- name: add docker apt repository
  apt_repository:
    repo: "{{ docker_apt_repo }}"
    state: present

- name: install docker components
  apt:
    update_cache: yes
    name:
      - "{{ containerd_pkg }}"
      - "{{ docker_ce_pkg }}"
      - "{{ docker_ce_cli_pkg }}"
    state: present
  
- name: copy daemon.json configuration
  copy:
    src: daemon.json
    dest: "{{ daemon_json_dest }}" 

- name: create /etc/systemd/system/docker.service.d
  file:
    path: /etc/systemd/system/docker.service.d
    state: directory

- name: restart docker service
  systemd:
    name: docker
    daemon_reload: yes
    state: restarted


