- name: get workers memory
  hosts: workers
  become: no
  gather_facts: yes

  tasks:
    - name: Display Memory Stats
      debug:
        msg: "Free/Total MB: {{ ansible_memory_mb.real.free }}/{{ansible_memory_mb.real.total}}" 



