- name: power off kube-cluster
  hosts: kube-cluster
  become: yes
  become_method: sudo
  gather_facts: false
  
  tasks:
    - name: power off
      command: /sbin/shutdown -h now
      ignore_errors: true

