---
# vars file for k8s_master
k8s_gpg_key_url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
k8s_key_id: 54A647F9048D5688D7DA2ABE6A030B21BA07F4FB
k8s_repo: deb https://apt.kubernetes.io/ kubernetes-xenial main

# k8s verstions
kubeadm_pkg: kubeadm=1.17.*
kubelet_pkg: kubelet=1.17.*
kubectl_pkg: kubectl=1.17.*

kubelet_svc: kubelet
