---
# vars file for k8s_master

############################
##### Docker variables #####
############################
docker_key_url: https://download.docker.com/linux/ubuntu/gpg
docker_key_id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
# TODO make docker_apt_repo value dynamic
docker_apt_repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
daemon_json_dest: /etc/docker/daemon.json
containerd_pkg: containerd.io=1.2.10-3*
docker_ce_pkg: docker-ce=5:19.03*
docker_ce_cli_pkg: docker-ce-cli=5:19.03*



#################################
##### Kubernetess variables #####
#################################

k8s_gpg_key_url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
k8s_key_id: 54A647F9048D5688D7DA2ABE6A030B21BA07F4FB
k8s_repo: deb https://apt.kubernetes.io/ kubernetes-xenial main

# k8s verstions
kubeadm_pkg: kubeadm=1.17.*
kubelet_pkg: kubelet=1.17.*
kubectl_pkg: kubectl=1.17.*

kubelet_svc: kubelet


...
